# Generated by Django 5.2.8 on 2026-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=1000)),
                ('ramlow', models.IntegerField()),
                ('pricelow', models.IntegerField()),
                ('ramhigh', models.IntegerField()),
                ('pricehigh', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
