# Generated by Django 5.2.8 on 2026-03-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.IntegerField()),
                ('modelname', models.CharField(max_length=50)),
                ('modelprice', models.IntegerField()),
                ('pricemax', models.IntegerField()),
                ('pricelow', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('ctgid', models.IntegerField(primary_key=True, serialize=False)),
                ('ctgname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CtgBrands',
            fields=[
                ('brandid', models.IntegerField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=30)),
                ('brandimg', models.CharField(max_length=1000)),
                ('brandctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories')),
            ],
        ),
        migrations.CreateModel(
            name='processors',
            fields=[
                ('processorid', models.IntegerField(primary_key=True, serialize=False)),
                ('processorname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('ramid', models.IntegerField(primary_key=True, serialize=False)),
                ('rammax', models.CharField(max_length=40)),
                ('ramlow', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rom',
            fields=[
                ('romid', models.IntegerField(primary_key=True, serialize=False)),
                ('rommax', models.CharField(max_length=40)),
                ('romlow', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Iphone',
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='modelbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ctgbrands'),
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.processors'),
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='ramhigh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_ram_models', to='api.ram'),
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='ramlow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_ram_models', to='api.ram'),
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='lowrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_rom_models', to='api.rom'),
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='maxrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_rom_models', to='api.rom'),
        ),
    ]
