# Generated by Django 5.2.8 on 2026-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brandmodels_categories_ctgbrands_processors_ram_rom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodels',
            name='modelimage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
