# Generated by Django 5.2.8 on 2026-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ramlow_ram_ram_rename_romlow_rom_rom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodels',
            name='id',
        ),
        migrations.AlterField(
            model_name='brandmodels',
            name='modelid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
