# Generated by Django 5.2.8 on 2026-04-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_brandmodels_id_alter_brandmodels_modelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processors',
            old_name='processorname',
            new_name='processorbrand',
        ),
    ]
