# Generated by Django 5.2.8 on 2026-03-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brandmodels_modelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='ramlow',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='rom',
            old_name='romlow',
            new_name='rom',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='rammax',
        ),
        migrations.RemoveField(
            model_name='rom',
            name='rommax',
        ),
    ]
